# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-json
    - id: check-xml
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-executables-have-shebangs
    - id: requirements-txt-fixer
    - id: mixed-line-ending
    - id: check-byte-order-marker
    - id: check-ast
    - id: detect-private-key
    - id: check-vcs-permalinks
    - id: debug-statements
- repo: https://github.com/psf/black
  rev: 24.1.1
  hooks:
    - id: black
      language_version: python3.11
      args: ["--config=pyproject.toml"]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: [
        "--rcfile=pyproject.toml",
        "-rn", # Only display messages
        "-sn", # Don't display the score
        "--recursive=y"
      ]
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
      args: [
        "-v"
      ]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
      args: ["--settings-path=pyproject.toml"]
